version: "3.4"

x-default: &default
  restart: always
  logging:
    driver: "json-file"
    options:
      max-size: "50m"

services:
  nginx:
    <<: *default

    image: "nginx:latest"

    volumes:
      - ./services/nginx/templates:/etc/nginx/templates

    ports:
      - "80:80"
      - "443:443"

  postgres:
    <<: *default

    image: "postgres:14-alpine"

    environment:
      POSTGRES_USER: site
      POSTGRES_PASSWORD: site
      POSTGRES_DB: site

    ports:
      - "7777:5432"

    volumes:
      - ./postgres:/var/lib/postgresql/data

  site:
    <<: *default

    dockerfile: ./site/Dockerfile

    ports:
      - "8000:8000"

    depends_on:
      - nginx
      - postgres

  grafana:
    <<: *default

    build: ./services/grafana

    depends_on:
      - nginx

    ports:
      - "3000:3000"

    volumes:
      - grafana-storage:/var/lib/grafana

  prometheus:
    <<: *default

    build: ./services/prometheus

    depends_on:
      - grafana

    ports:
      - "127.0.0.1:9090:9090"

    volumes:
      - prometheus-storage:/prometheus

  cadvisor:
    <<: *default

    image: gcr.io/cadvisor/cadvisor:v0.44.0

    ports:
      - "127.0.0.1:8080:8080"

    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  node_exporter:
    <<: *default

    image: prom/node-exporter:v1.3.1

    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"

    volumes:
      - "/:/host:ro,rslave"

volumes:
  grafana-storage:
  prometheus-storage:
