version: "3.7"

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "10m"

x-restart-policy: &restart_policy
  restart: unless-stopped


services:
  nginx:
    <<: *logging
    <<: *restart_policy

    image: "nginx:latest"

    volumes:
      - ./services/nginx/templates:/etc/nginx/templates

    ports:
      - "80:80"
      - "443:443"

  postgres:
    <<: *logging
    <<: *restart_policy

    image: "postgres:latest"

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U xythrion"]
      interval: 2s
      timeout: 1s
      retries: 5

    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  site:
    <<: *logging
    <<: *restart_policy

    dockerfile: ./site/Dockerfile

    ports:
      - "8000:8000"

    depends_on:
      - nginx
      - postgres

  grafana:
    <<: *logging
    <<: *restart_policy

    build: ./services/grafana

    depends_on:
      - nginx

    ports:
      - "3000:3000"

    volumes:
      - grafana-storage:/var/lib/grafana

  prometheus:
    <<: *logging
    <<: *restart_policy

    build: ./services/prometheus

    depends_on:
      - grafana

    ports:
      - "127.0.0.1:9090:9090"

    volumes:
      - prometheus-storage:/prometheus

  cadvisor:
    <<: *logging
    <<: *restart_policy

    image: gcr.io/cadvisor/cadvisor:v0.44.0

    ports:
      - "127.0.0.1:8080:8080"

    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  node_exporter:
    <<: *logging
    <<: *restart_policy

    image: prom/node-exporter:v1.3.1

    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"

    volumes:
      - "/:/host:ro,rslave"

volumes:
  grafana-storage:
  prometheus-storage:
